### ISSUE TITLE
Creating another table instead of using JSON in the database

### ISSUE THREAD

**Issue by Retriever5500** [Navid-Ebadi-2003/spotify_project#10]
Currently, we're using JSON in our database for playlists, likes and etc. This could be considered a bad design, more on this here:
https://stackoverflow.com/questions/20219503/is-it-bad-design-to-use-arrays-within-a-database
My proposed solution is to introduce another table that stores the history of all things, like creation of playlists, follows, likes and other stuff.
We'd have three columns. The first one would be the initiator of an action(like liking or following), second being the type of the action and the third being the user/artist/playlist that the action is being done upon. That has several advantages over what we're using currently:
1: In the approach we're using currently, if we wanted to add a follower to someone we'd first have to find the JSON string of that particular user then convert it to a json and finally add the user to the json. With the new approach we simply have to to insert a new row on the table.
2: If we wanted to get the list of all users who had liked a playlist, we'd have to search all of users to see if they liked a playlist or not with the old approach. With the new one, it's as simple as creating a query that searches for the action type and the playlist that was acted upon(i.e liking that particular playlist).
What are your oipinions @MMDPROJECT @Navid-Ebadi-2003

**Comment by MMDPROJECT** [comment]
Well first I appreciate your work on database structures of the project.

I realized that you don't want to pull out a whole `Json` and manipulate it for only an specific property of that and then put that back into table or push it to the client, I think you want to be able to easily change or see an specific property that we need, for that you want to create a new table of actions that could handle that for us. Well I would say that seems very clever and good to me, and I think we will have no problem to merge the new changes into the structures. 
  
But there is still something that would like to ask; We still put the information from database queries into an specific template of `Json` that we already have in the `Response` right?
@Retriever5500

**Comment by MMDPROJECT** [comment]
But can you provide more information about the three columns that you have considered for that table please?
Initiator is the id of who has done the action ?
action type is something like followed, liked, created playlist, liked playlist?
and the third column is id of the entity the action is done upon ? 
@Retriever5500

**Comment by Retriever5500** [comment]
> I realized that you don't want to pull out a whole Json and manipulate it for only an specific property of that and then put that back into table or push it to the client, I think you want to be able to easily change or see an specific property that we need, for that you want to create a new table of actions that could handle that for us. Well I would say that seems very clever and good to me, and I think we will have no problem to merge the new changes into the structures.

Yes, thanks.

>But there is still something that would like to ask; We still put the information from database queries into an specific template of Json that we already have in the Response right?

Yes correct. It's not difficult at all to extract the corresponding JSON.

**Comment by Retriever5500** [comment]
> But can you provide more information about the three columns that you have considered for that table please?
Initiator is the id of who has done the action ?

Yeah sure.

> action type is something like followed, liked, created playlist, liked playlist?
and the third column is id of the entity the action is done upon ?

Yeah correct.

For example, imagine that a user is liking a music. The initiator(subject) would be the user, the action would be the USER_LIKE_TRACK or something like that, and the object(something being acted upon) would be the music.

Another one: Imagine a track being added to a playlist. The subject would be the playlist, action would be PLAYLIST_ADD_TRACK and object would be the track.
@MMDPROJECT

**Comment by Retriever5500** [comment]
And while we're at it, I think it's better if we make the fact that a playlist is private or public a property of the playlist itself, not the user.

**Comment by MMDPROJECT** [comment]
@Retriever5500 alright i see. Then lets do that.

**Comment by Retriever5500** [comment]
solved with #11
