### ISSUE TITLE
Queries Issue

### ISSUE THREAD

**Issue by MMDPROJECT** [Navid-Ebadi-2003/spotify_project#24]
Please look at the code:
`public static synchronized JsonObject getPlaylist(UUID playlistId) {
        final String query = """
                SELECT * FROM Playlist
                WHERE playlist_id=?;
                """;

        try {
            PreparedStatement pstmt = connection.prepareStatement(query);
            pstmt.setString(1, playlistId.toString());
            ResultSet rs = pstmt.executeQuery();
            if(rs.next()) {
                JsonObject albumJson = new JsonObject();
                albumJson.addProperty("playlistId", playlistId.toString());

                String title = rs.getString("title");
                albumJson.addProperty("title", title);

                String description = rs.getString("description");
                albumJson.addProperty("description", description);

                String userId = rs.getString("user_id");
                albumJson.addProperty("userId", userId);

                int popularity = rs.getInt("popularity");
                albumJson.addProperty("popularity", popularity);

                int isPrivate = rs.getInt("is_private");
                albumJson.addProperty("isPrivate", isPrivate);

                JsonArray tracks = getObjectsFromHistory(playlistId, "PLAYLIST_ADD_TRACK");
                albumJson.add("tracks", tracks);

                return albumJson;
            } else {
                // If null, then that means the album doesn't exist
                return null;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
}
`

Why we don't put **profilePath** to the **JsonObject**
@Retriever5500

**Comment by Retriever5500** [comment]
Oh I see, I think I forgot. Will create a PR soon

**Comment by MMDPROJECT** [comment]
Please look at the code :

```
`public static synchronized JsonObject getMusic(UUID trackId) {
    final String query = """
            SELECT * FROM Music
            WHERE track_id=?;
            """;
    
    try {
        PreparedStatement pstmt = connection.prepareStatement(query);
        pstmt.setString(1, trackId.toString());
        ResultSet rs = pstmt.executeQuery();
        if(rs.next()) {
            JsonObject musicJson = new JsonObject();
            musicJson.addProperty("trackId", trackId.toString());
    
            String title = rs.getString("title");
            musicJson.addProperty("title", title);
    
            String artistId = rs.getString("artist_id");
            musicJson.addProperty("artistId", artistId);
    
            String albumId = rs.getString("album_id");
            musicJson.addProperty("albumId", albumId);
    
            String genreId = rs.getString("genre_id");
            musicJson.addProperty("genreId", genreId);
    
            int duration = rs.getInt("duration");
            musicJson.addProperty("duration", duration);
    
            String releaseDate = rs.getString("release_date");
            musicJson.addProperty("releaseDate", releaseDate);
    
            int popularity = rs.getInt("popularity");
            musicJson.addProperty("popularity", popularity);
    
            return musicJson;
        } else {
            // If null, then that means the track doesn't exist
            return null;
        }
    } catch (SQLException e) {
        e.printStackTrace();
        return null;
    }
}
`

```
shouldn't we change `String artistId = rs.getString("artist_id");` to `JsonArray artistId = rs.getAsJsonArray("artist_id")` becase artist_id contains multiple artists, i know the name of it is little bit weird and you confused for that but please reconsider.

@Retriever5500

**Comment by Retriever5500** [comment]
wait there can be multiple artists?

**Comment by MMDPROJECT** [comment]
> wait there can be multiple artists?

Yes unfortunately

**Comment by MMDPROJECT** [comment]
Please look at the code :

```
public static synchronized JsonObject getMusic(UUID trackId) {
        final String query = """
                SELECT * FROM Music
                WHERE track_id=?;
                """;

        try {
            PreparedStatement pstmt = connection.prepareStatement(query);
            pstmt.setString(1, trackId.toString());
            ResultSet rs = pstmt.executeQuery();
            if(rs.next()) {
                JsonObject musicJson = new JsonObject();
                musicJson.addProperty("trackId", trackId.toString());

                String title = rs.getString("title");
                musicJson.addProperty("title", title);

                String artistId = rs.getString("artist_id");
                musicJson.addProperty("artistId", artistId);

                String albumId = rs.getString("album_id");
                musicJson.addProperty("albumId", albumId);

                String genreId = rs.getString("genre_id");
                musicJson.addProperty("genreId", genreId);

                int duration = rs.getInt("duration");
                musicJson.addProperty("duration", duration);

                String releaseDate = rs.getString("release_date");
                musicJson.addProperty("releaseDate", releaseDate);

                int popularity = rs.getInt("popularity");
                musicJson.addProperty("popularity", popularity);

                return musicJson;
            } else {
                // If null, then that means the track doesn't exist
                return null;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
    }
```

i think we should also put the `profilePath` & `trackPath` to the `JsonObject`

**Comment by Retriever5500** [comment]
> Yes unfortunately

Then I think we have to add another thing to history, because as we discussed we don't want to have JSON inside our records, plus even tho it'd be easy to get the the artists of a music, it wouldn't be easy to get the the music of artists, as we have to search in musics to look for a given artist

**Comment by Retriever5500** [comment]
Actually, we don't need to. we can simply get the artists by using the function `getSubjectsFromHistory` with `ARTIST_ADD_TRACK`. So I only have to replace it with a function.

**Comment by MMDPROJECT** [comment]
> Actually, we don't need to. we can simply get the artists by using the function `getSubjectsFromHistory` with `ALBUM_ADD_TRACK`. So I only have to replace it with a function.

Yes i suppose.

**Comment by Retriever5500** [comment]
Okay, will get on it too. Let me know if you have any other ideas/questions. I'll finish the queries soon.

**Comment by MMDPROJECT** [comment]
> Okay, will get on it too. Let me know if you have any other ideas/questions. I'll finish the queries soon.

Alright as i write the codes i will review other parts as i can and tell the issues, thanks for your attention.

**Comment by MMDPROJECT** [comment]
```
// Get an album's info from id
    public static synchronized JsonObject getAlbum(UUID albumId) {
        final String query = """
                SELECT * FROM Album
                WHERE album_id=?;
                """;

        try {
            PreparedStatement pstmt = connection.prepareStatement(query);
            pstmt.setString(1, albumId.toString());
            ResultSet rs = pstmt.executeQuery();
            if(rs.next()) {
                JsonObject albumJson = new JsonObject();
                albumJson.addProperty("albumId", albumId.toString());

                String title = rs.getString("title");
                albumJson.addProperty("title", title);

                String artistId = rs.getString("artist_id");
                albumJson.addProperty("artistId", artistId);

                String genreId = rs.getString("genre_id");
                albumJson.addProperty("genreId", genreId);

                String releaseDate = rs.getString("release_date");
                albumJson.addProperty("releaseDate", releaseDate);

                int popularity = rs.getInt("popularity");
                albumJson.addProperty("popularity", popularity);

                JsonArray tracks = getObjectsFromHistory(albumId, "ALBUM_ADD_TRACK");
                albumJson.add("tracks", tracks);

                return albumJson;
            } else {
                // If null, then that means the album doesn't exist
                return null;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
    }
```

also i think that we need to put `profilePath` here as well
@Retriever5500

**Comment by MMDPROJECT** [comment]
in `upload` methods i need a returned template like this for `usersResult`: `[{"userId" : %s, "username" : %s, "email" : %s, "password" : %s, "profilePath" : %s}, ...]` 
but as i look through the queries we don't have such a thing till now, could please provide a method for that.
@Retriever5500

**Comment by MMDPROJECT** [comment]
Also please look at this code :

```
public void uploadWatchUserPage(JsonObject jsonResults) throws IOException {
        //  Template of jsonResult:
        // {
        // "userId:             %s,
        // "username:           %s,
        // "email:              %s,
        // "address:            %s,
        // "password:           %s,
        // "profilePath:        %s,
        // "createdPlaylists:  [%s],
        // "likedPlaylists:    [%s],
        // "followers:         [%s],
        // "followings:        [%s]
        //  }

        // Parsing Results
        String profilePath = jsonResults.get("profilePath").getAsString();
        JsonArray createdPlaylistsJson = jsonResults.getAsJsonArray("createdPlaylists");
        JsonArray likedPlaylistsJson = jsonResults.getAsJsonArray("likedPlaylists");

        // Uploading profile pictures
        uploadProfilePic(profilePath);
        uploadProfilePics(createdPlaylistsJson);
        uploadProfilePics(likedPlaylistsJson);
    }
```

 in this `upload` method i need a format like a provided above but as i look into `queries` i can't find a method for that, could you please provide one for that too?
 @Retriever5500

**Comment by Retriever5500** [comment]
Okay where is this? You're trying to get the info of a user to watch their page? If so, why do we need their password? Anyways creating this is easy, will created a method for it
@MMDPROJECT

**Comment by MMDPROJECT** [comment]
> Okay where is this? You're trying to get the info of a user to watch their page? If so, why do we need their password? Anyways creating this is easy, will created a method for it @MMDPROJECT

No in the code i provided, the information i wanted is that for visiting page of a user

**Comment by Retriever5500** [comment]
Okay... why do we need their password tho? Also I think the property "address" is unnecessary

**Comment by MMDPROJECT** [comment]
> Okay... why do we need their password tho? Also I think the property "address" is unnecessary

Yes you are completly right and i agree but i think for simplicity we can do that, but if you say so we can delete unnecessary information from the `Jsons`, tell me your opinion please @Retriever5500

**Comment by Retriever5500** [comment]
Yeah actually it wouldn't be difficult to remove a line of code. Let's just remove it.

**Comment by MMDPROJECT** [comment]
> Yeah actually it wouldn't be difficult to remove a line of code. Let's just remove it.

Affirmative I will do that. but I have to only remove unnecessary from template of `usersResult` right? 
@Retriever5500

**Comment by Retriever5500** [comment]
Yeah

**Comment by MMDPROJECT** [comment]
> Yeah

Alright.

**Comment by MMDPROJECT** [comment]
#22 @Retriever5500 Sorry I forgot to say that a `album` could belong to multiple `artists`. I know the name of it's column in **database** is weird and I apologize.

**Comment by MMDPROJECT** [comment]
#22 @Retriever5500 if you agree we can remove ability to like a `album` in our program. if so please remove the `getLikedAlbums`.

**Comment by Retriever5500** [comment]
Oh I see, okay will make the corresponding changes after I made some samples

**Comment by MMDPROJECT** [comment]
@Retriever5500  @Navid-Ebadi-2003 
In below I will tell things that we will need to change in queries:

1. In queries in method `getArtist`, `getMusic`, `getAlbum`, `getPlaylist`, `getUser`. please add a property called `fileName` to specify the name of the file that we are going to **upload** and **download**. (there is no need to have two `fileName` for a music beucase their format is different). (Also please don't forget to add this property while inserting data into **database**, (we need to add such a column to tables too)).

2. Please add `"creator" : {"userId" : %s, "username" : %s}` to `getPlaylist` .

3. Please add `"artists" : [{"artistName" : %s, "artistId" : %s}]` to `getAlbum` .

4. Please add `"artists" : [{"artistId" : %s, "artistName" : %s}, ...]` to `getMusic` .

Below I will attach a file for better understanding of new **Json** formats as well.
[jsonFormats.txt](https://github.com/Navid-Ebadi-2003/spotify_project/files/11842281/jsonFormats.txt)

**Comment by Retriever5500** [comment]
Okay will get on it

**Comment by Retriever5500** [comment]
@MMDPROJECT why are we adding `artists` to `getArtist()`?

**Comment by MMDPROJECT** [comment]
> @MMDPROJECT why are we adding `artists` to `getArtist()`?

Sorry we don't have to, that was just misclick, I haven't provided that in the [JsonFromats](https://github.com/Navid-Ebadi-2003/spotify_project/files/11842281/jsonFormats.txt) too
