### ISSUE TITLE
Uploading the whole mp3 or sending cover in separate?

### ISSUE THREAD

**Issue by MMDPROJECT** [Navid-Ebadi-2003/spotify_project#29]
@Retriever5500 man isn't it a little bit hard for us to pull out `profilePicture` of each of the `musics` and send them separate from it's mp3s?

**Comment by Retriever5500** [comment]
Dw I'll make the samples. A script will do

**Comment by Retriever5500** [comment]
Okay so, what do you think is the right approach? Have a directory dedicated to covers or extract the covers while we want to send the them? @MMDPROJECT @Navid-Ebadi-2003

**Comment by MMDPROJECT** [comment]
> Okay so, what do you think is the right approach? Have a directory dedicated to covers or extract the covers while we want to send the them? @MMDPROJECT @Navid-Ebadi-2003

In the `upload` methods that I provided I assumed that the `profilePath` of a track is passed separate from it's `trackPath` and this probably means that cover of that track is stored somewhere. So I think that is gonna be easier if we have a directory for covers instead of extracting covers and then send them
