### ISSUE TITLE
Database Architectures

### ISSUE THREAD

**Issue by MMDPROJECT** [Navid-Ebadi-2003/spotify_project#30]
@Retriever5500 One question : don't we have to delete the `artist_id` column from **Table** Music ?

**Comment by Retriever5500** [comment]
Yeah you're right, we don't need it anymore as we're using `History` instead.

**Comment by MMDPROJECT** [comment]
> Yeah you're right, we don't need it anymore as we're using `History` instead.

Alright, I will remote it
