### ISSUE TITLE
Confusing branches

### ISSUE THREAD

**Issue by MMDPROJECT** [Navid-Ebadi-2003/spotify_project#33]
@Retriever5500 One question: Man there are sometimes that we Have a branch A and B (Both their source is C), and we do some works on A and then switch to B and do some other works there as well, and also we need some of the updates in A and we should merge A into B, everything looks fine until that we get to the point that we want to merge B into remote and see that there are some unrelated changes with branch B, that's because of the merging A into B in the middle of the work. what should we do to prevent that?

**Comment by MMDPROJECT** [comment]
@Retriever5500 
Also do you agree that we merge all the branches that we have made till now to the dev of navid and start branching again from dev? because there are many branches for now and it's a little bit confusing for me.

**Comment by Retriever5500** [comment]
Yeah I agree, let's do that

**Comment by Retriever5500** [comment]
Okay so I indeed told you to delete them, probably wasn't thinking straight, sorry xD

**Comment by MMDPROJECT** [comment]
> Okay so I indeed told you to delete them, probably wasn't thinking straight, sorry xD

It's alright and cleared RN, so don't worry about it.
