### ISSUE TITLE
Providing samples in the database

### ISSUE THREAD

**Issue by Retriever5500** [Navid-Ebadi-2003/spotify_project#41]
Is it necessary to write the java code that extracts tracks data and puts them in the database, or can we do anything we want?
@MMDPROJECT @Navid-Ebadi-2003

**Comment by MMDPROJECT** [comment]
> Is it necessary to write the java code that extracts tracks data and puts them in the database, or can we do anything we want? @MMDPROJECT @Navid-Ebadi-2003

I think it's not necessary, and we can put the track data to the database how ever we like, but could you please explain what you are exactly going to do ?
