### ISSUE TITLE
Providing the files for the server

### ISSUE THREAD

**Issue by Retriever5500** [Navid-Ebadi-2003/spotify_project#44]
So the total file size is 60MB currently, which is a ton. Do you think we should upload it somewhere and provide a link in Readme to download it or do you prefer it to be in Git? @MMDPROJECT @Navid-Ebadi-2003

**Comment by MMDPROJECT** [comment]
> So the total file size is 60MB currently, which is a ton. Do you think we should upload it somewhere and provide a link in Readme to download it or do you prefer it to be in Git? @MMDPROJECT @Navid-Ebadi-2003

As I talked with @Navid-Ebadi-2003 we think that's better to upload it somewhere else and then provide link in README.md
@Retriever5500
